### ISSUE TITLE
Troubles compiling packages in rad studio 10

### ISSUE THREAD

**Issue by genuch** [beNative/dduce#1]
Hello. I tried to install packages in rad studio 10 and ran into some troubles.
1st, there was no dcp for virtualtrees library included in the project (VirtualTreesDR), so, I`ve dowloaded and installed  Virtual Treeview v6.3, then changed method names to match Ilogger interface in DDuce.components.virtualdataset.pas (EnterMethod -->Enter; ExitMethod-->Leave) (see pic.1)
![pic 1 virtualdataset errors](https://cloud.githubusercontent.com/assets/19746408/15799216/793d7b90-2a5d-11e6-90e4-47a71fda3dd3.png)
After that, i get the following errors in DDuce.Components.LogTree.pas:

> [dcc32 Error] DDuce.Components.LogTree.pas(123): E2037 Declaration of 'DoGetImageIndex' differs from previous declaration
> [dcc32 Error] DDuce.Components.LogTree.pas(274): E2033 Types of actual and formal var parameters must be identical

(pic.2) 
![pic 2 logtree errors](https://cloud.githubusercontent.com/assets/19746408/15799245/7e572328-2a5e-11e6-893a-4837e4618411.png)
I must be doing something wrong here. I really appreciate any help you can provide.

**Comment by beNative** [comment]
Hi,
The packages need some work to get them working, and I will fix that soon. I still need to do some work on the visual components and the designtime packages.

The demos and unit tests should work without installing packages. 

In the mean time you can check out my other project [Concepts](https://github.com/beNative/Concepts) which includes a copy of DDuce and all the dependent libraries needed to get everything working. The compiling issues I see from your screenshots should be resolved with the Virtualtreeview version which is included in this project.

**Comment by beNative** [comment]
Hi,

See my comment in [https://github.com/beNative/dduce/issues/3](https://github.com/beNative/dduce/issues/3)
Build instructions will be added soon. Let me know if you still experience any problems.
