### ISSUE TITLE
Can't compile beNative/LogViewer because of error in dduce

### ISSUE THREAD

**Issue by luebbe** [beNative/dduce#3]
Hi Folks,

I have no problem compiling and running the tests for dduce after adding some paths to the spring libraries.
However I never succeed in compiling [LogViewer](https://github.com/beNative/LogViewer), because of the following fatal error in DDuce.ObjectInspector.zObjectInspector.pas:

`[dcc32 Fataler Fehler] DDuce.ObjectInspector.zObjectInspector.pas(31): F2613 Unit 'zObjInspector' nicht gefunden.`

I'm not able to find (via grep search): zObjInspector, zObjInspTypes and TzObjectInspector, TzObjectHost in any of the mentioned depenencies.

Where can I find those files?

**Comment by beNative** [comment]
Hi,
You need following libraries (use my own forked versions):
[https://github.com/beNative/zcontrols](https://github.com/beNative/zcontrols) 
[https://github.com/beNative/Delphi-ZeroMQ](https://github.com/beNative/Delphi-ZeroMQ)
[https://github.com/beNative/TBCEditor](https://github.com/beNative/TBCEditor)

Please note that the project is still premature and more documentation and build instructions will be added soon.
